# Configuración del autoencoder U-net con skip connections
# NOTA: Las clases están definidas en el notebook y se registran como notebook_models
_target_: notebook_models.UNetAutoencoder

architecture: "unet"  # Para logging y naming

input_channels: 3
latent_dim: 128

encoder_channels: [64, 128, 256, 512]
decoder_channels: [512, 256, 128, 64]

