# Configuración del entrenador
max_epochs: 50
learning_rate: 0.001
weight_decay: 1e-5

# Optimizador
optimizer: "adam"  # adam, sgd
momentum: 0.9  # Solo para SGD

# Scheduler
scheduler:
  name: "step"  # step, cosine, plateau
  step_size: 15
  gamma: 0.5
  patience: 5  # Para plateau
  factor: 0.5  # Para plateau

# Early Stopping
early_stopping:
  enabled: true
  monitor: "val/loss"
  mode: "min"
  patience: 10
  min_delta: 0.001

# Checkpointing
checkpoint:
  save_top_k: 3
  monitor: "val/loss"
  mode: "min"
  save_last: true

# Otros
gradient_clip_val: 1.0
accumulate_grad_batches: 1


