# Configuración del autoencoder U-Net (Modelo C)
_target_: notebook_models.UNetAutoencoder

architecture: "unet_autoencoder"

input_channels: 3
latent_dim: 128

encoder_channels: [64, 128, 256, 512]
decoder_channels: [512, 256, 128, 64]

# Embedding dimension (para detección de anomalías)
embedding_dim: 128


